### ISSUE TITLE
[Proposal]: Command Execution Check

### ISSUE THREAD

**Issue by Nageshbansal** [steadybit/extension-kubernetes#93]
### Summary

Command Execution checks can be a good choice for executing/running shell commands and verification for experiments.
The idea of this check arises from the "Command Probes" in litmuschaos, an open-source chaos engineering Platform.

## Motivation 

Checks allow users to run their verification criteria before, during, and after the experiments. Steadybit has plenty number of checks, specifically for Kubernetes. Still, it lacks the check that can be used to run bash shell commands within experiment pods or the defined images to check the specific data within a database, parse the value out of a JSON blob that is dumped into a particular path, or check for the existence of a specific string in the service logs.

#### Align Mode
The Align Mode is executed from within the Extension pod. It is preferred for simple shell commands. It is the default mode and can be tuned by omitting the source field.
![alignMode](https://github.com/steadybit/extension-kubernetes/assets/76246968/4b39ee96-c833-4e15-885e-c1907374b01f)

**Note: I've already implemented this Mode and will raise the PR if the community agrees on the Proposal**

##### Demo:
Logs:
![Logs](https://github.com/steadybit/extension-kubernetes/assets/76246968/a7de72a9-5a10-418f-96b9-e8bdfe4360d5)
Platform: 
![Platform_Preview](https://github.com/steadybit/extension-kubernetes/assets/76246968/198d4b0c-9a99-44b9-bd6c-9058f7633ff3)

### Source Mode

In source mode, the command execution is carried out from within a new pod whose image can be specified. It can be used when application-specific binaries are required.

![SourceMode](https://github.com/steadybit/extension-kubernetes/assets/76246968/0bd872ee-eb8f-49f9-bfa5-67efe3ea2e31)
Reference:
- Litmuschaos Docs: https://docs.litmuschaos.io/docs/concepts/probes#cmdprobe

**Comment by nilswloka** [comment]
As discussed in Slack, the suggested capability would work on a level that clashes with two of Steadybit's product principles: Firstly, to use it effectively, the user would have to be inherently familiar with the implementation details of the underlying infrastructure, whereas Steadybit aims to be easily usable by non-experts. Secondly, and more importantly, it would allow circumventing the target-based permission concept by granting the user the ability to execute arbitrary scripts with the privileges of the container running the K8s extension.

Thus, we will not consider this for inclusion in extension-kubernetes.
